# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

AllCops:
  TargetRubyVersion: 4.0
# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false

Style/StringLiterals:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Layout/CaseIndentation:
  Enabled: false

Metrics/ClassLength:
  Enabled: true
  CountComments: true
  Max: 48
  Include:
      - 'app/**/*'

Metrics/ModuleLength:
  Enabled: true
  CountComments: true
  Max: 40
  Include:
      - 'app/**/*'

Layout/LineLength:
  Enabled: true
  Max: 120
  Include:
      - 'app/**/*'
